### PR TITLE
Minimal config for make works with kaminari

### PR DESCRIPTION
**Pull request by ceritium**
This is a early pull request, I want know what do you think about this.

The idea is make the gem configurable, you can define the name of the methods, this allow make compatible with other gems.

TODO: 
- [x] Add some tests.
- [x] Include generators for kaminari and will_paginate.
- [x] Add more methods configurables
- [x] Allow send per_page and page as params to the helper or use the config.

### CODE REVIEW

**Comment by bacarini** [comment]
Hi @ceritium, sorry for the late answer and thanks for all work you have done so far.

Well, I like the idea to let stuff configurable but I believe this it not necessary when we are using  `kaminari` and `will_paginate`. I figure out a way to do that. You can look at #2.

Also, pagination links is not as [json-api](http://jsonapi.org/examples/) says it should be. So, [this PR](https://github.com/bacarini/jbuilder_pagination/pull/2) is to fix that. I will be very thankful if you can review it and let your thoughts as well. :smiley: 
 
I come up if that idea based on [another PR](https://github.com/rails-api/active_model_serializers/pull/1041) on `ActiveModel::Serializer`.

**Comment by bacarini** [comment]
I am closing this PR since the new version works well with `kaminari` and `will_paginate`. But tks so much for the work you put here man. I really appreciate it. :+1:

**Comment by ceritium** [comment]
Ok, no problem. If the problem is solved I am happy.

Also I see that json-api recommend this format "page[number]=3&page[size]=1".
Anyway, do you think that could be interesting allow customize it?

**Comment by bacarini** [comment]
How would you customize it?

Just remember, that the gem follows the [json-api spec](http://jsonapi.org/format/#fetching-pagination) and [its examples](http://jsonapi.org/examples/)

**Comment by ceritium** [comment]
Allow to change the parameters for pagination. This does not follow the json-api spec but could be useful for legacy code.

PS:  I do not need this feature.

**Pull request closed without merging**
